# Generated by Django 2.0.1 on 2018-01-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histogram',
            old_name='num_bad_posture',
            new_name='is_bad_posture',
        ),
    ]
